<h1>Login</h1>
<?php

if ($errors) {
    foreach($errors as $error) {
        echo '<div class="alert alert-danger" role="alert"><strong>', $error, '</strong></div>';
    }
}

?>
<div class="row">
    <div class="col-md-6">
        <form action="" method="post">
            <label style="display:block">Username </label><input id="username" name="username" type="text" value="<?php echo htmlspecialchars($form['username'])?>" placeholder="phpdev">
            <label style="display:block;margin-top:7px;">Password (home) </label><input id="password" name="password" type="password" value="<?php echo htmlspecialchars($form['password'])?>">
            <div style="margin:17px 0;"><button class="btn btn-lg btn-primary" type="submit">Sign in</button></div>
        </form>
    </div>
</div>
